# Generated by Django 3.1.7 on 2021-03-10 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPUInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_interface', models.CharField(max_length=15, verbose_name='GPU interface')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(max_length=15, verbose_name='Memory type')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title/name')),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Manufacturer')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('modification_date', models.DateField(auto_now=True)),
                ('capacity', models.CharField(blank=True, max_length=15, null=True, verbose_name='Size/Capacity')),
                ('memory_speed', models.CharField(blank=True, max_length=15, null=True, verbose_name='Memory Speed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket_title', models.CharField(max_length=15, verbose_name='Socket title')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title/name')),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Manufacturer')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('modification_date', models.DateField(auto_now=True)),
                ('form_factor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Form Factor')),
                ('chipset', models.CharField(blank=True, max_length=20, null=True, verbose_name='Chipset')),
                ('memory_chanel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Memory Channel')),
                ('audio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Audio')),
                ('internal_slots', models.TextField(verbose_name='Internal Connectivity')),
                ('external_slots', models.TextField(verbose_name='External Connectivity')),
                ('cpu_socket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.socket', verbose_name='CPU Socket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title/name')),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Manufacturer')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('modification_date', models.DateField(auto_now=True)),
                ('architecture', models.CharField(blank=True, max_length=50, null=True, verbose_name='Architecture')),
                ('cores', models.CharField(blank=True, max_length=4, null=True, verbose_name='Cores')),
                ('threads', models.CharField(blank=True, max_length=4, null=True, verbose_name='Threads')),
                ('clock_speed', models.CharField(blank=True, max_length=10, null=True, verbose_name='Clock Speed')),
                ('turbo_speed', models.CharField(blank=True, max_length=10, null=True, verbose_name='Turbo Speed')),
                ('max_memory_size', models.CharField(blank=True, max_length=10, null=True, verbose_name='Max. Memory Size')),
                ('max_memory_speed', models.CharField(blank=True, max_length=15, null=True, verbose_name='Max. Memory Speed')),
                ('integrated_graphics', models.CharField(blank=True, max_length=100, null=True, verbose_name='Integrated Graphics')),
                ('cpu_socket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.socket', verbose_name='CPU Socket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
